version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: moneylens-api
    environment:
      - ML_API_HOST=0.0.0.0
      - ML_API_PORT=8000
      - ML_API_DEBUG=${ML_API_DEBUG:-false}
      - ML_MAX_FILE_SIZE=${ML_MAX_FILE_SIZE:-10485760}
      - ML_UPLOAD_DIR=/app/uploads
      - ML_ALLOWED_EXTENSIONS=${ML_ALLOWED_EXTENSIONS:-pdf}
      - ML_OCR_ENABLED=${ML_OCR_ENABLED:-true}
      - ML_OCR_LANGUAGE=${ML_OCR_LANGUAGE:-eng}
      - ML_TEXT_EXTRACTION_TIMEOUT=${ML_TEXT_EXTRACTION_TIMEOUT:-30}
      - ML_DATABASE_URL=${ML_DATABASE_URL:-sqlite:///./moneylens.db}
    volumes:
      - api_uploads:/app/uploads
      - api_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - moneylens-network

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: moneylens-web
    environment:
      - VITE_API_URL=/api
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - moneylens-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: moneylens-nginx
    ports:
      - "${ML_NGINX_PORT:-80}:80"
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - moneylens-network

volumes:
  api_uploads:
    driver: local
  api_data:
    driver: local

networks:
  moneylens-network:
    driver: bridge